In [13]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [14]:
drug = pd.read_csv('../ASCII/DRUG26Q1.txt',sep="$",encoding="latin-1")
drug.head()

,primaryid,caseid,drug_seq,role_cod,drugname,prod_ai,val_vbm,route,dose_vbm,cum_dose_chr,cum_dose_unit,dechal,rechal,lot_num,exp_dt,nda_num,dose_amt,dose_unit,dose_form,dose_freq
0,1001678127,10016781,1,PS,SANDOSTATIN,OCTREOTIDE ACETATE,1,Subcutaneous,"UNK, TID (cont 02 weeks post 01st LAR)",NaN,NaN,Y,U,NaN,NaN,19667.0,NaN,NaN,NaN,TID
1,1001678127,10016781,2,SS,SANDOSTATIN,OCTREOTIDE ACETATE,1,Intramuscular,"20 mg, QMO",NaN,NaN,Y,U,NaN,NaN,19667.0,20.0,MG,NaN,/MONTH
2,1001678127,10016781,3,SS,SANDOSTATIN,OCTREOTIDE ACETATE,1,Intramuscular,"20 mg, QMO",NaN,NaN,Y,U,NaN,NaN,19667.0,20.0,MG,NaN,/MONTH
3,1001678127,10016781,4,SS,SANDOSTATIN LAR DEPOT,OCTREOTIDE ACETATE,1,Intramuscular,"20 mg, QMO (once a month)",NaN,NaN,U,NaN,NaN,NaN,19667.0,20.0,MG,NaN,/MONTH
4,1001678127,10016781,5,SS,SANDOSTATIN LAR DEPOT,OCTREOTIDE ACETATE,1,Intramuscular,"30 mg, QMO (once a month)",NaN,NaN,U,NaN,NaN,NaN,19667.0,30.0,MG,NaN,/MONTH

In [15]:
drug.info()

<class 'pandas.DataFrame'>
RangeIndex: 1703210 entries, 0 to 1703209
Data columns (total 20 columns):
 #   Column         Dtype
---  ------         -----
 0   primaryid      int64
 1   caseid         int64
 2   drug_seq       int64
 3   role_cod       str
 4   drugname       str
 5   prod_ai        str
 6   val_vbm        int64
 7   route          str
 8   dose_vbm       str
 9   cum_dose_chr   float64
 10  cum_dose_unit  str
 11  dechal         str
 12  rechal         str
 13  lot_num        str
 14  exp_dt         float64
 15  nda_num        float64
 16  dose_amt       float64
 17  dose_unit      str
 18  dose_form      str
 19  dose_freq      str
dtypes: float64(4), int64(4), str(12)
memory usage: 259.9 MB

In [16]:
drug.shape

(1703210, 20)

In [17]:
drug.isnull().sum()

primaryid              0
caseid                 0
drug_seq               0
role_cod               0
drugname               6
prod_ai            35272
val_vbm                0
route             788704
dose_vbm          480509
cum_dose_chr     1671961
cum_dose_unit    1671961
dechal            714633
rechal           1395551
lot_num          1331352
exp_dt           1700918
nda_num          1128764
dose_amt         1036943
dose_unit        1036943
dose_form        1069365
dose_freq        1338498
dtype: int64

In [18]:
drug = drug[['primaryid', 'drugname', 'prod_ai', 'role_cod', 'route']]
drug.shape

(1703210, 5)

In [19]:
reac = pd.read_csv('../ASCII/REAC26Q1.txt',sep='$',encoding ='latin-1')
reac.head()

    primaryid    caseid                        pt drug_rec_act
0  1001678127  10016781                  Erythema          NaN
1  1001678127  10016781  Blood creatine increased          NaN
2  1001678127  10016781                      Fall          NaN
3  1001678127  10016781                      Scab          NaN
4  1001678127  10016781                   Rosacea          NaN

In [20]:
reac.shape

(1330675, 4)

In [21]:
reac.isnull().sum()

primaryid             0
caseid                0
pt                    0
drug_rec_act    1328076
dtype: int64

In [22]:
reac = reac[['primaryid','pt']]
reac.shape

(1330675, 2)

In [23]:
outc = pd.read_csv("../ASCII/OUTC26Q1.txt",sep='$',encoding = 'latin-1')
outc.head()

    primaryid    caseid outc_cod
0  1001678127  10016781       OT
1   100293665  10029366       OT
2  1005762126  10057621       HO
3   100670805  10067080       OT
4   100716524  10071652       OT

In [24]:
outc.isnull().sum()

primaryid    0
caseid       0
outc_cod     0
dtype: int64

In [25]:
outc = outc[['primaryid', 'outc_cod']]
outc.shape

(291580, 2)